const data = {
    jobs: [
      {
        _id: '1',
        name: 'ADOBE',
        position: 'Software engineer',
        vacancy : 10,
        salary: 50000,
        count_applicants: 10,
        description: 'WE ARE IN NEED OF SOFTWARE ENGINEER!!',
      },
      {
        _id: '2',
        name: 'WALMART',
        position: 'Software engineer',
        vacancy : 10,
        salary: 60000,
        count_applicants: 5,
        description: 'WE ARE IN NEED OF SOFTWARE ENGINEER!!',
      },
      {
        _id: '3',
        name: 'VISA',
        position: 'Software engineer',
        vacancy : 5,
        salary: 50000,
        count_applicants: 5,
        description: 'WE ARE IN NEED OF SOFTWARE ENGINEER!!',
      },
      {
        _id: '4',
        name: 'DE SHAW',
        position: 'Technical Analyst',
        vacancy : 5,
        salary: 80000,
        count_applicants: 5,
        description: 'WE ARE IN NEED OF A TECHNICAL ANALYST!!',
      },
      {
        _id: '5',
        name: 'GOOGLE',
        position: 'Software engineer',
        vacancy : 3,
        salary: 80000,
        count_applicants: 5,
        description: 'WE ARE IN NEED OF SOFTWARE ENGINEER!!',
      },
      {
        _id: '6',
        name: 'MICROSOFT',
        position: 'Software engineer',
        vacancy : 7,
        salary: 70000,
        count_applicants: 5,
        description: 'WE ARE IN NEED OF SOFTWARE ENGINEER!!',
      },
      {
        _id: '7',
        name: 'GOLDMAN SACHS',
        position: 'Technical Analyst',
        vacancy : 5,
        salary: 80000,
        count_applicants: 5,
        description: 'WE ARE IN NEED OF A TECHNICAL ANALYST!!',
      },
    ],
};
export default data;