export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_APPLICATION_DETAILS = 'CART_SAVE_APPLICATION_DETAILS';
export const CART_EMPTY = 'CART_EMPTY';